apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: &namespace&
  name: ft-front
spec:
  selector:
    matchLabels:
      app: ft-front
  replicas: 1
  template:
    metadata:
      labels:
        app: ft-front
    spec:
      containers:
        - name: ft-front
          image: &imagen_ecr&:&version_image&
          env:
            - name: TZ
              value: America/Bogota
            - name: LANG
              value: C.UTF-8
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          volumeMounts:
            - name: frontend-fichas-tecnicas-volume
              mountPath: /usr/share/nginx/html/js/app.js
              subPath: app.js
            - name: frontend-fichas-tecnicas-volume
              mountPath: /usr/share/nginx/html/js/chunk-vendor.js
              subPath: chunk-vendor.js
            - name: conf-timezone-volumen
              mountPath: /etc/localtime
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
      dnsPolicy: ClusterFirst
      volumes:
        - name: conf-timezone-volumen
          hostPath:
            path: /usr/share/zoneinfo/America/Bogota
        - name: frontend-fichas-tecnicas-volume
          persistentVolumeClaim:
            claimName: pvc-frontend-fichas-tecnicas
